# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20160815_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latlon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
