# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20160815_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latlon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
