# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20160816_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(unique=True),
        ),
    ]
