# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20160818_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latlon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
