# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20160813_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
