# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20160815_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='connoisseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
