# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20160815_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
